"""empty message

Revision ID: 99398bfc9095
Revises: 
Create Date: 2017-09-16 15:48:13.056453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99398bfc9095'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('listId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listId'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('list')
    # ### end Alembic commands ###
